### ISSUE TITLE
Add support for AWS EBS

### ISSUE THREAD

**Issue by rajikaimal** [scorelab/nodecloud#17]
# This is a Feature Proposal

## Description

Add support for AWS EBS,
- [ ] Create image
- [ ] Attach image
- [ ] Create volume
- [ ] Delete volume
- [ ] Describe snapshots
- [ ] Describe volume
- [ ] Describe multiple volumes

### TODO:

- [ ] Describe volume modifications
- [ ] Detach volume
- [ ] Import image
- [ ] Import snapshot
- [ ] Import volume
- [ ] Modify volume
- [ ] Start instance (EBS backed AMI instance)
- [ ] Stop instance (EBS backed AMI instance)

**Comment by rehrumesh** [comment]
@rajikaimal sometimes GCP may not provide all these functionalities in their storage api. Identify common functionalities and implement them first. You can remove the rest of the task from this issue and move them into a different issue for future implementation.

**Comment by rajikaimal** [comment]
@rehrumesh Got it, I'll do a comparison.
